CLEANUP_BASE_ACTION_SPACE_SIZE = 9
HARVEST_BASE_ACTION_SPACE_SIZE = 8
SWITCH_BASE_ACTION_SPACE_SIZE = 8

REWARD_UPPER_BOUND = 60

EPSILON_CONSTANT = 1

PERIODIC_PERT_FREQUENCY = 135 * 10**3
SINGLE_PERT_FREQUENCY = 500 * 10**3
